### ISSUE TITLE
Error in measurement check (suspect due to lack of fork_lengths)

### ISSUE THREAD

**Issue by adriankitch** [aae-stats/aae.data#12]
This is the error message (data attached):

Quitting from lines 170-231 [measurement-check] (qaqc.Rmd)
Error in `combine_vars()`:
! Faceting variables must have at least one value
Backtrace:
 1. base::print(p)
 2. ggplot2:::print.ggplot(p)
 4. ggplot2:::ggplot_build.ggplot(x)
 5. layout$setup(data, plot$data, plot$plot_env)
 6. ggplot2 (local) setup(..., self = self)
 7. self$facet$compute_layout(data, self$facet_params)
 8. ggplot2 (local) compute_layout(..., self = self)
 9. ggplot2::combine_vars(data, params$plot_env, vars, drop = params$drop)
[Copy of AAE_standard_data_entry_template_Gellibrand 2023.csv](https://github.com/aae-stats/aae.data/files/11844383/Copy.of.AAE_standard_data_entry_template_Gellibrand.2023.csv)

**Comment by jdyen** [comment]
Addressed in [6a25b0e](https://github.com/aae-stats/aae.data/commit/6a25b0e771094a409b1d1078aac5e9e7190fce27). Due to all NA values in the measurements (fork length), as you suggested. Now checks for these when preparing the report and prints a statement that all values were NA if this occurs.
