### ISSUE TITLE
Error is thrown if there are no lengths recorded in the data.

### ISSUE THREAD

**Issue by adriankitch** [aae-stats/aae.data#13]
Error is thrown if there are no lengths recorded in the data.

`Quitting from lines 170-231 [measurement-check] (qaqc.Rmd)
Error in `combine_vars()`:
! Faceting variables must have at least one value
Backtrace:
1. base::print(p)
2. ggplot2:::print.ggplot(p)
4. ggplot2:::ggplot_build.ggplot(x)
5. layout$setup(data, plot$data, plot$plot_env)
6. ggplot2 (local) setup(..., self = self)
7. self$facet$compute_layout(data, self$facet_params)
8. ggplot2 (local) compute_layout(..., self = self)
9. ggplot2::combine_vars(data, params$plot_env, vars, drop = params$drop)`

**Comment by jdyen** [comment]
Didn't we update this in the latest version? (#12)

**Comment by adriankitch** [comment]
I don't think so. This is from Frank and I got him to update to the latest version. He doesn't have any length data so the LW charts seem to fall over. The previous fix was for no fork lengths.

**Comment by jdyen** [comment]
Should all be the same fix (fork lengths, weights, and total lengths). Can you get Frank to send me the data and I'll have a look? I'm suspicious given the error is identical to the previous error.

**Comment by jdyen** [comment]
Fixed in [cac4d8a](https://github.com/aae-stats/aae.data/commit/cac4d8a36eedb269b7c739e4a63398025b3ca903)
